# Generated by Django 4.1.5 on 2023-02-04 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product", options={"verbose_name": "상품", "verbose_name_plural": "상품"},
        ),
        migrations.RenameField(
            model_name="product", old_name="stuck", new_name="stock",
        ),
    ]
