# Generated by Django 4.1.7 on 2023-02-19 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fcuser", "0002_fcuser_level"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fcuser",
            name="password",
            field=models.CharField(max_length=128, verbose_name="비밀번호"),
        ),
    ]
